name: example
description: An AWS CloudWatch wrapper package for easy Flutter cloud logging. Currently only logging is supported.
version: 0.5.0
homepage: https://github.com/Zsmerritt/Flutter_AWS_CloudWatch
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  aws_cloudwatch:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
